
#semantic Segmentation ( duck semantic segmentation)---------------------------------------

path: C:/Users/HP/Downloads/Semantic Segmentation duck
train: images/train
val: images/val
nc: 1
names: ['duck']

